### ISSUE TITLE
Create storage dir automatically

### ISSUE THREAD

**Issue by 3demax** [emlun/btsync-autoconfig#15]
It would be nice to create storage dir alongside with genereating the conf automatically.
It took me a few minutes to figure out why btsync is not starting with proper config.

BTW thanks for this neat script!

**Comment by emlun** [comment]
> It would be nice to create storage dir alongside with genereating the conf automatically.

Is that necessary? I seem to remember that btsync would do it automatically. I'll look into it. Thanks for the suggestion!

> BTW thanks for this neat script!

Thanks for using it!

**Comment by emlun** [comment]
It indeed seems like btsync does not create the storage directory. Thanks for the report!

```
Process: 16187 ExecStart=/usr/bin/btsync --config %h/.config/btsync/btsync.conf --nodaemon (code=exited, status=1/FAILURE)
feb 17 03:43:44 hugin btsync[16187]: Storage path specified in config file does not exist.
feb 17 03:43:44 hugin systemd[1]: btsync@btstest.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by emlun** [comment]
Should be solved by 139b70a76ea3fa99d9144e184b73a1de407bd788. Don't hesitate to report any future bugs or feature requests!

**Comment by 3demax** [comment]
Thank you very much!

**Comment by 3demax** [comment]
To be honest, my biggest feature request is for btsync to be open source :) Your software is totally fine.

**Comment by emlun** [comment]
Agreed. :)
